### ISSUE TITLE
Drag python file into editor when not working on main.py

### ISSUE THREAD

**Issue by microbit-robert** [microbit-foundation/python-editor-v3#538] opened 2022-02-03 14:10 UTC
When dragging a python file into the editor while not working on the `main.py` file, the resulting dialog always offers to replace the code in `main.py`, but not the currently open file, which could be misleading.

![image](https://user-images.githubusercontent.com/95928279/152358936-c3d5e6dd-e569-46ae-93eb-1222e6de850b.png)

**Comment by microbit-matt-hillsdon** [comment] 2022-10-10 12:06
This is working as intended and the dialog makes it clear what will happen. The process of uploading third-party modules that don't have a magic module marker isn't very clear and would be good to revisit in future but this aspect probably isn't a priority. Closing.

**Closed by microbit-matt-hillsdon** 2022-10-10 12:06 UTC
